### ISSUE TITLE
Create Certified Kubernetes YAML

### ISSUE THREAD

**Issue by dankohn** [cncf/filterable-landscape#48]
Please create YAML with the 64 entries listed on https://docs.google.com/spreadsheets/d/1LxSqBzjOxfGx3cmtZ4EbB_BGCxT_wlxW_xgHVVa23es/edit#gid=0 with the logos from https://www.cncf.io/certification/software-conformance/. Then include the 28 KCSPs listed on https://docs.google.com/spreadsheets/d/1frS9VkVEJ0OHK6wHDYyvJkGQp0QCn5ioXaV0f7K3GDE/edit#gid=0 with the logos from https://kubernetes.io/partners/

YAML:

```yaml
landscape:
  - category: 
    name: "Special"
    subcategories:
      - subcategory:
        name: "Certified Kubernetes"
        items:
        - item:
          name: "Alauda EE"
          company: "Alauda"
          description:
          certified_kubernetes: "Platform"
          homepage_url: https://www.alauda.cn/product/detail/id/68.html
          logo: https://www.cncf.io/wp-content/uploads/2017/11/alauda.png
          crunchbase: https://www.crunchbase.com/organization/alauda
        - item:
          name: "Elastic Container Service for Kubernetes (EKS)"
          company: "Amazon Web Services"
          description: "Amazon Elastic Container Service for Kubernetes (Amazon EKS) is a managed service that makes it easy for you to run Kubernetes on AWS without needing to install and operate your own Kubernetes clusters."
          certified_kubernetes: false
          homepage_url: https://aws.amazon.com/eks/
          logo: https://cdn-images-1.medium.com/max/1600/1*5YAnP-tNi1Tkjzk1urIJYw.png
          crunchbase: https://www.crunchbase.com/organization/amazon
      - subcategory:
        name: "Kubernetes Certified Service Provider"
        items:
        - item:
          name: "Bitnami"
          company: "Bitnami"
          description: "Bitnami brings a catalog of trusted, up to date, and easy to use applications and application building blocks to Kubernetes."
          homepage_url: https://bitnami.com/kubernetes
          logo: https://www.cncf.io/wp-content/uploads/2017/03/logo_bitnami_17-300x184.png
          crunchbase: https://www.crunchbase.com/organization/bitnami
```
Note that the open source Kubernetes products should include a `repo_url`. `certified_kubernetes` can be `product`, `distribution`, or `false`.
